spring:
  output:
    ansi:
      enabled: always

  # DB
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_ID}
    password: ${DB_USER_PW}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  # SMTP
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_ID}
    password: ${SMTP_PW}
    properties:
      debug: true
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true

# Spring Security
jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: ${JWT_VALID_TIME}